### ISSUE TITLE
Different Behavior on Different Platforms and with different python versions

### ISSUE THREAD

**Issue by sdfgeoff** [cwacek/python-jsonschema-objects#105]
I recently discovered that this library behaves significantly differently on different platforms (Includes different versions of python as well as across operating systems). I cannot detect rhyme or reason behind why it works on some and not on others.

-----------------------------------------------------------

On some systems (Python 3.5.2, Kubuntu and Python 3.6.2, Archlinux) , it works well (the way it is meant(?) to work), whereby a json file like:  
```{'somename':3}```

can be parsed and validated using the ObjectBuilder, and then used in python:  
```print(parsed_objects.somename > 4)  # False```

-----------------------------------------------------------

And on another system (python 3.6.2, Windows) components need to be converted explicitly:  
```print(parsed_objects.somename > 4) ```
    TypeError: '>' not supported between instances of 'DummyJson/some_name' and 'int'

However I can explicitly convert it:  
```print(int(parsed_objects.somename) > 4)  # False```

I could live with this I suppose.

-----------------------------------------------------------

On yet another platform (python 3.6.1m Ubuntu Minimal and python 3.5.2m Ubuntu Minimal and python 3.5.? on Linux Mint), any schema, including "{}" results in the traceback below. (But it works in the non-m version)
```
Traceback (most recent call last):
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/dist-packages/python_jsonschema_objects/__init__.py", line 43, in __init__
        'memory': self.memory_resolver
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/dist-packages/jsonschema/validators.py", line 318, in from_schema
        return cls(schema.get(u"id", u""), schema, *args, **kwargs)
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/dist-packages/jsonschema/validators.py", line 295, in __init__
        self.store.update(store)
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/_collections_abc.py", line 839, in update
        if isinstance(other, Mapping):
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/abc.py", line 191, in __instancecheck__
        return cls.__subclasscheck__(subclass)
...
Repeat following ad infinitum:
...
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/typing.py", line 1145, in __subclasscheck__
        return super().__subclasscheck__(cls)
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/typing.py", line 877, in __extrahook__
        if issubclass(subclass, scls):
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/typing.py", line 1145, in __subclasscheck__
        return super().__subclasscheck__(cls)
...
Until
...
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/abc.py", line 197, in __subclasscheck__
        if subclass in cls._abc_cache:
      File "/home/sdfgsdfg/bin/blender/build_linux/bin/2.78/python/lib/python3.6/_weakrefset.py", line 72, in __contains__
        wr = ref(item)
    RecursionError: maximum recursion depth exceeded while calling a Python object
```

I have not done a comprehensive survey of OS's and python versions, and am completely unsure as to why there are differences between platforms.

I'm aware there isn't enough information here for this to be a 'proper' issue, but was wondering if people had observed similar behaviors?

**Comment by agoose77** [comment]
Related see /issues/105 and /issues/113
