### ISSUE TITLE
Arrays without "items" fail to serialize

### ISSUE THREAD

**Issue by iandanforth** [cwacek/python-jsonschema-objects#16]
I don't believe "items" is required by the spec, but appears to be required by the serializer

Traceback (most recent call last):
  File "/home/idanforth/fetch/src/sandbox/fetchcore/test/unit/test_scheduler.py", line 99, in test_init_scheduler
    print new_task.serialize()
  File "/usr/local/lib/python2.7/dist-packages/python_jsonschema_objects/classbuilder.py", line 154, in serialize
    return enc.encode(self)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/python_jsonschema_objects/util.py", line 40, in default
    props[raw] = getattr(obj, trans)
  File "/usr/local/lib/python2.7/dist-packages/python_jsonschema_objects/classbuilder.py", line 141, in __getattr__
    name, self.__class__.__name__))
AttributeError: errors is not a valid property of task

Object property that fails:

        "errors": {
            "id": "errors",
            "type": "array",
            "description": "Errors not associated with any goals",
            "required": false
        },

Object property that succeeds:

        "errors": {
            "id": "errors",
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Errors not associated with any goals",
            "required": false
        },

**Comment by davek2** [comment]
Is it possible to generate a decoder when the type of the decoded items is not known?  If "items" is omitted from a schema, a validator will accept anything as valid.  But how can a python class represent "anything" except as raw JSON text?

**Comment by cwacek** [comment]
As @davek2, I'm not sure it's possible to handle the case where there is no type, because we can't generate any sort of reasonable wrapper for it. The only solution would be store it as JSON, but that sort of defeats the purpose.
