### ISSUE TITLE
Pattern need to be supported.

### ISSUE THREAD

**Issue by edward-twine** [cwacek/python-jsonschema-objects#182]
I would like to define a property that accept certain type of string value that comply to certain pattern.  Furthermore, would like to see `patternProperties` be supported too.  The following is the stack tace:
```text
Traceback (most recent call last):
  File "/Users/laedwar/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/laedwar/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/laedwar/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/laedwar/DataRoot/Work/github/data_services/model/manuallife.py", line 95, in <module>
    _ns = _pjsbuilder.build_classes()
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/__init__.py", line 149, in build_classes
    builder.construct(nm, self.schema, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 494, in construct
    ret = self._construct(uri, *args, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 508, in _construct
    klasses = self.construct_objects(clsdata["oneOf"], uri)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 775, in construct_objects
    for i, item_detail in enumerate(oneOfList)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 775, in <listcomp>
    for i, item_detail in enumerate(oneOfList)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 494, in construct
    ret = self._construct(uri, *args, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 583, in _construct
    self.resolved[uri] = self._build_object(uri, clsdata, parent, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 654, in _build_object
    self.resolved[uri] = self.construct(uri, detail, (ProtocolBase,))
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 494, in construct
    ret = self._construct(uri, *args, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 583, in _construct
    self.resolved[uri] = self._build_object(uri, clsdata, parent, **kw)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/classbuilder.py", line 740, in _build_object
    nm, clsdata, self
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/site-packages/python_jsonschema_objects/pattern_properties.py", line 57, in __init__
    PatternDef(pattern=re.compile(pattern), schema_type=typ)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/Users/laedwar/.local/share/virtualenvs/data_services-007GfXcq/lib/python3.7/sre_parse.py", line 580, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range a-Z at position 13'
```

The following is my schema:

```python
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://json-schema.org/draft/2019-09/schema",
    "title": "SymbolWeightsSchema",
    "description": "Symbol Weights",

    "type": "object",
    "oneOf": [
        {   "properties": {
                "updated_at": {
                    "type": "string",
                    "format": "date",
                    "description": "The datetime this record was updated on."
                },
                "template_type": {
                    "enum": [ "short_term", "retirement" ],
                    "description": "The template type: short_term, retirement."
                },
                "portfolio_type": {
                    "enum": [ "conservative", "moderate", "aggressive" ],
                    "description": "The portfolio type: conservative, moderate, aggressive."
                },
                "years_to_goal": {
                    "type": "integer",
                    "description": "The years to reach the goal."
                },
                "symbol": {
                    "type": "string",
                    # python_jsonschema_objects doesn't support pattern.
                    "pattern": "^[A-Za-z][A-Za-Z-]{0,4}[A-Za-z]{0,1}$",
                    "description": "The investment symbol."
                },
                "weight": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1,
                    "description": "The fractional value allocated for the given symbol."
                }
            },
            "minProperties": 5,
            "required": [ "template_type", "portfolio_type", "years_to_goal", "symbol" ],
            "additionalProperties": false
        },
        {   "properties": {
                "updated_at": {
                    "type": "string",
                    "format": "date",
                    "description": "The datetime this record was updated on."
                },
                "template_type": {
                    "enum": [ "short_term", "retirement" ],
                    "description": "The template type: short_term, retirement."
                },
                "portfolio_type": {
                    "enum": [ "conservative", "moderate", "aggressive" ],
                    "description": "The portfolio type: conservative, moderate, aggressive."
                },
                "years_to_goal": {
                    "type": "integer",
                    "description": "The years to reach the goal."
                },
                "allocations": {
                    "type": "object",
                    "patternProperties": {
                        # python_jsonschema_objects doesn't support pattern.
                        "^[A-Za-z][A-Za-Z-]{0,4}[A-Za-z]{0,1}$": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 1,
                            "description": "The weight for the investment symbol key."
                        }
                    },
                    "minProperties": 1,
                    "maxProperties": 10,
                    "description": "The flatten symbol/weight pairs for a given unique 'template_type/portfolio_type/years_to_goal' combination."
                }
            },
            "minProperties": 4,
            "required": [ "template_type", "portfolio_type", "years_to_goal" ],
            "additionalProperties": false
        },
    ]
}
```

**Comment by edward-twine** [comment]
I found a work around.  You can delete this issue.

The problem is the pattern `[A-Za-Z-]` with the extra dash at the end.  I tried escaping it with a `\` and it still doesn't work.  "Fortunately", my use case is to test for uppercase so I change it to `^[A-Z][ABCDEFGHIJKLMNOPQRSTUVBWXYZ-]{0,4}[A-Z]{0,1}$`
