### ISSUE TITLE
Request to release already implemented dependency bugfix (jsonschema 4.x.y).

### ISSUE THREAD

**Issue by suoniq** [cwacek/python-jsonschema-objects#227]
Hi Chris,

with the latest major release of pjo's jsonschema dependency (4.x.y) you get an import error in version 0.4.0:
```bash
$ pip list
Package                           Version
--------------------------------- -------
...
jsonschema                        4.1.2
...
python-jsonschema-objects         0.4.0
...
$ python
Python 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_jsonschema_objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/dvlp/workspace/python-jsonschema-objects/python_jsonschema_objects/__init__.py", line 12, in <module>
    from jsonschema.compat import iteritems
ModuleNotFoundError: No module named 'jsonschema.compat'
```
I wanted to provide a fix but noticed that this issue is already solved on master:
```bash
$ pip list
Package                           Version          Location
--------------------------------- ---------------- -------------------------------------------
...
jsonschema                        4.1.2
...
python-jsonschema-objects         0.4.0+2.gca06e73 c:/dvlp/workspace/python-jsonschema-objects
$ python
Python 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_jsonschema_objects
>>> 
```
All what is needed to publish 0.4.1. What do you think? (Okay, okay, extending the tox tests to jsonschema40 and 41 is needed...)

**Comment by cwacek** [comment]
I tagged the latest version so it should build and publish now. Sorry for the delay - I couldn't figure out how to do that from my phone and couldn't get to a full machine at a reasonable time.
