### ISSUE TITLE
following $refs with relative file paths

### ISSUE THREAD

**Issue by mzbenami** [cwacek/python-jsonschema-objects#26]
Hey, would someone be able to tell me how to correctly format relative file paths or my calls to ``ObjectBuilder()`` so that ``build_classes()`` works?

What I am trying:
```python
builder = pjs.ObjectBuilder('facts.json')
ns = builder.build_classes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/__init__.py", line 83, in build_classes
    builder.construct(nm, self.schema)
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 288, in construct
    ret = self._construct(uri, *args, **kw)
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 362, in _construct
    parent)
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 458, in _build_object
    typ = self.construct(uri, detail['items'])
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 288, in construct
    ret = self._construct(uri, *args, **kw)
  File "/Library/Python/2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 341, in _construct
    with self.resolver.resolving(uri) as resolved:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/jsonschema/validators.py", line 296, in resolving
    raise RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: [Errno 2] No such file or directory: u'ase.json'
```

**facts.json**:
```
{
    "title": "facts schema",
    "type": "object",
    "properties": {
        "interfaces": {
            "type": "array",
            "items": {"$ref": "base.json#/definitions/interface"}
        },
        "os": {"type": "string"},
        "platform": {"type": "string"},
        "hostname": {"type": "string"},
        "kickstart_image": {"type": "string"},
        "last_reboot_reason": {"type": "string"},
        "modules": {
            "type": "array",
            "items": {"$ref": "file://base.json#/definitions/module"}
        },
        "power_supply_info": {
            "type": "array",
            "items": {"$ref": "file://base.json#/definitions/ps_info"}
        },
        "fan_info": {
            "type": "array",
            "items": {"$ref": "file://base.json#/definitions/fans"}
        },
        "vlan_list": {
            "type": "array"
        }
    },
    "required": ["platform"]
}
```

**base.json** (same directory as **facts.json**):
```
{
    "title": "base schema",
    "definitions": {
        "interface": {
            "type": "object",
            "properties": {
                "interface": {"type": "string"},
                "description": {"type": ["string", "null"]},
                "state": {"type": "string"},
                "vlan": {"type": ["string", "null", "number"]},
                "duplex": {"type": "string"},
                "speed": {"type": ["string", "number"]},
                "type": {"type": "string"}
            },
            "required": ["interface", "description", "state", "duplex", "speed"]
        },

        "module": {
            "type": "object",
            "properties": {
                "ports": {"type": "number"},
                "type": {"type": "string"},
                "model": {"type": "string"},
                "status": {"type": "string"}
            }
        },

        "ps_info": {
            "type": "object",
            "properties": {
                "number": {"type": "number"},
                "model": {"type": "string"},
                "actual_output": {"type": "string"},
                "actual_input": {"type": ["string", "null"]},
                "total_capacity": {"type": "string"},
                "status": {"type": "string"}
            },
            "required": ["number", "model", "status"]
        },

        "fan_info": {
            "id": "#fans",
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "model": {"type": "string"},
                "hw_ver": {"type": "string"},
                "direction": {"type": "string"},
                "status": {"type": "string"}
            },
            "required": ["name", "status"]
        }
    }
}
```

**Comment by cwacek** [comment]
I believe the issue is that file URIs have 3 slashes. So
`file:///base.json` instead of `file://base.json`. It's interpreting the
`b` as the host location. See [this](
http://superuser.com/questions/352133/why-do-file-urls-start-with-3-slashes)
for more.

**Comment by cwacek** [comment]
I believe the issue is that file URIs have 3 slashes. So `file:///base.json` instead of `file://base.json`. It's interpreting the `b` as the host location. See [this](http://superuser.com/questions/352133/why-do-file-urls-start-with-3-slashes) for more.
