### ISSUE TITLE
facing an issue when running the library with logging set as DEBUG

### ISSUE THREAD

**Issue by farshidce** [cwacek/python-jsonschema-objects#41]
Traceback (most recent call last):
  File "/Users/farshid/flab/careabout/schema/functests/testgenerated.py", line 141, in test_WebResponse
    obj = Factory.WebResponse()
  File "/Users/farshid/flab/careabout/schema/src/careaboutschema/generated/factory.py", line 142, in WebResponse
    clazz = load_classes('webresponse.001.json').WebResponse
  File "/Users/farshid/flab/careabout/schema/src/careaboutschema/util.py", line 37, in load_classes
    loaded_classes[filename] = builder.build_classes()
  File "/Users/farshid/flab/careabout/schema/venv/lib/python3.5/site-packages/python_jsonschema_objects/__init__.py", line 83, in build_classes
    builder.construct(nm, self.schema)
  File "/Users/farshid/flab/careabout/schema/venv/lib/python3.5/site-packages/python_jsonschema_objects/classbuilder.py", line 388, in construct
    logger.debug(util.lazy_format("Constructing {0}", uri))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1267, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/Users/farshid/flab/careabout/schema/venv/lib/python3.5/site-packages/nose/plugins/logcapture.py", line 82, in emit
    self.buffer.append(self.format(record))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 328, in getMessage
    msg = str(self.msg)
TypeError: __str__ returned non-string (type NoneType)

i was able to fix this by adding a return to this line to the lazy_format class

 14     def __str__(self):
 15         return self.fmt.format(*self.args, **self.kwargs)

will send a patch shortly

**Comment by cwacek** [comment]
Fixed in #42
