### ISSUE TITLE
Bad handling of arrays of mixed types objects

### ISSUE THREAD

**Issue by lbonn** [cwacek/python-jsonschema-objects#49]
(or at least inconsistent with `jsonschema`)

Here is a minimal test case:

```
schema_good = {
    'title': 'example',
    'type': 'array',
    'items': {
        'oneOf': [
            {
                'type': 'object',
                'properties': {
                    'a': {
                        'type': 'string',
                    }
                },
                'required': [ 'a' ],
            },
            {
                'type': 'object',
                'properties': {
                    'b': {
                        'type': 'string',
                    }
                },
                'required': [ 'b' ],
            },
        ]
    },
}

instance = [{'a': ''}, {'b': ''}]
```

`jsonschema` validates our instance but `build_classes()` crashes:

```
Traceback (most recent call last):
  File "schema.py", line 70, in <module>
    pjs.ObjectBuilder(schema_bad).build_classes()
  File ".../python_jsonschema_objects/__init__.py", line 83, in build_classes
    builder.construct(nm, self.schema)
  File ".../python_jsonschema_objects/classbuilder.py", line 418, in construct
    ret = self._construct(uri, *args, **kw)
  File ".../python_jsonschema_objects/classbuilder.py", line 474, in _construct
    **clsdata_copy)
  File ".../python-jsonschema-objects/python_jsonschema_objects/validators.py", line 317, in create
    elif isdict and item_constraint['type'] == 'array':
KeyError: 'type'
```

If we remove the `required` arrays in both objects, `build_classes()` terminates but `jsonschema` is unable to validate the instance anymore:

```
jsonschema.exceptions.ValidationError: {'a': ''} is valid under each of {'properties': {'b': {'type': 'string'}}, 'type': 'object'}, {'properties': {'a': {'type': 'string'}}, 'type': 'object'}

Failed validating 'oneOf' in schema['items']:
    {'oneOf': [{'properties': {'a': {'type': 'string'}}, 'type': 'object'},
               {'properties': {'b': {'type': 'string'}}, 'type': 'object'}]}

On instance[0]:
    {'a': ''}
```

**Comment by cwacek** [comment]
@lbonn I'll take a look at this when I get a chance.
