### ISSUE TITLE
TypeError exception from build_classes

### ISSUE THREAD

**Issue by craigwin-ni** [cwacek/python-jsonschema-objects#5]
Hi Chris,
I'm just starting with python-javaschema-objects trying to learn the process.  I started with the metaschema from http://json-schema.org/draft-04/schema (figured it was good) and ran the following short program with the debug messaging activated:

  builder = pjs.ObjectBuilder(METASCHEMA)
  print "builder:", builder
  ns = builder.build_classes()
  print "ns:", ns

METASCHEMA is the path to the file containing the schema.  The output is below.
(This is python 2.7.8 on windows 7.)
Thanks,  Craig

-> python test1.py
builder: <python_jsonschema_objects.ObjectBuilder object at 0x01718A90>
DEBUG:root:Constructing http://json-schema.org/draft-04/schema#/definitions/simpleTypes
DEBUG:root:Constructed <class 'python_jsonschema_objects.classbuilder.http://json-schema.org/draft-04/schema#/definitions/simpleTypes'>
DEBUG:root:Constructing http://json-schema.org/draft-04/schema#/definitions/schemaArray
Traceback (most recent call last):
  File "test1.py", line 25, in <module>
    ns = builder.build_classes()
  File "c:\Users\Craig\.virtualenvs\stillsim\lib\site-packages\python_jsonschema_objects\__init__.py", line 79, in build_classes
    builder.construct(uri, defn)
  File "c:\Users\Craig\.virtualenvs\stillsim\lib\site-packages\python_jsonschema_objects\classbuilder.py", line 287, in construct
    ret = self._construct(uri, *args, **kw)
  File "c:\Users\Craig\.virtualenvs\stillsim\lib\site-packages\python_jsonschema_objects\classbuilder.py", line 372, in _construct
    elif 'type' in clsdata and issubclass(clsdata['type'], ProtocolBase):
  File "c:\Users\Craig\.virtualenvs\stillsim\lib\abc.py", line 184, in __subclasscheck__
    cls._abc_negative_cache.add(subclass)
  File "c:\Users\Craig\.virtualenvs\stillsim\lib\_weakrefset.py", line 86, in add
    self.data.add(ref(item, self._remove))
TypeError: cannot create weak reference to 'unicode' object

**Comment by ferringb** [comment]
This is a pretty poor error, but it means that your schema definition is actually wrong.  For example, doing the following would trigger it:

"Blah": {
   "properties": {
      "type": "array",
      "item": { "type": "string" }
   }
}

^^^ Note the typo of 'item' instead of 'items'; python-jsonschema-objects should instead be throwing a jsonp failure, instead of exposing the underlying abc.meta idiocy.
