### ISSUE TITLE
Validate types and requirements in $ref definitions

### ISSUE THREAD

**Issue by 7048730** [cwacek/python-jsonschema-objects#58]
Hello there,

thank you for your useful python package! I ran into an issue when using the validation function. My test json passes validation although the value of "price" is of type `string` while the schema requires it to be of type `number`.
(FYI Elements listed  `require` within `definitions` could also be dropped without failing validation, which is not included in this example).

Here ist my example:

```
import python_jsonschema_objects as pjs

builder = pjs.ObjectBuilder(schema)
builder.validate(test)
```

My json (test):

```
{
    "id": 42,
    "cars": [{
        "name": "test",
        "price": "321"
    }]
}
```

My schema (schema):

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "test",
    "type": "object",
    "description": "testtest",
    "definitions": {
        "cars": {
            "type": "array",
            "properties": {
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            },
            "required": ["name", "price"]
        },
        "properties": {
            "id": {
                "type": "integer"
            },
            "cars": {
                "$ref": "#/definitions/cars"
            }
        },
        "required": [
            "id",
            "cars"
        ]
    }
}
```

**Comment by cwacek** [comment]
That's interesting, because you're not actually using the object builder and validator. That call just calls the JSON4Validator directly. To get this libraries functionality, you need to call `build_classes()` as shown in the README.

Your particular issue is because the JSON4Validator expects to be given a *string*, not an object, and apparently returns silently when given an object:

```
>>> builder.validate({"Hi": 4})
>>> builder.validate("""{"Hi": 4}""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python_jsonschema_objects/__init__.py", line 77, in validate
    raise ValidationError(e)
python_jsonschema_objects.validators.ValidationError: '{"Hi": 4}' is not of type u'object'

Failed validating u'type' in schema:
    {u'$schema': u'http://json-schema.org/draft-04/schema#',
     u'definitions': {u'cars': {u'properties': {u'name': {u'type': u'string'},
                                                u'price': {u'type': u'number'}},
                                u'required': [u'name', u'price'],
                                u'type': u'array'},
                      u'properties': {u'cars': {u'$ref': u'#/definitions/cars'},
                                      u'id': {u'type': u'integer'}},
                      u'required': [u'id', u'cars']},
     u'description': u'testtest',
     u'title': u'test',
     u'type': u'object'}

On instance:
    '{"Hi": 4}'
```
